language: elixir
os: linux
dist: xenial

otp_release:
  - 21
elixir:
  - 1.9

jobs:
  include:
    - elixir: "1.9"
      otp_release: "20.3"
    - elixir: "1.9"
      otp_release: "21.3"
    - elixir: "1.9"
      otp_release: "22.3"
    - elixir: "1.10"
      otp_release: "21.3"
    - elixir: "1.10"
      otp_release: "22.3"
    - elixir: "1.11"
      otp_release: "21.3"
    - elixir: "1.11"
      otp_release: "22.3"
    - elixir: "1.11"
      otp_release: "23.1"

env:
  global:
    - MIX_ENV=test

cache:
  directories:
    - _build
    - deps
    - priv/plts

install:
  - mix local.rebar --force; mix local.hex --force; mix deps.get

script:
  - mix compile
  - mix credo --strict
  - mix dialyzer
  - mix test
  - mix coveralls.travis
#deploy:
#  provider: script
#  script: >-
#    mix deps.get &&
#    mix hex.config username "$HEX_USERNAME" &&
#    (mix hex.config encrypted_key "$HEX_ENCRYPTED_KEY" > /dev/null 2>&1) &&
#    (echo "$HEX_PASSPHRASE"\\nY | mix hex.publish) &&
#    mix clean &&
#    mix deps.clean --all
#  on:
#    tags: true
